export type Lesson = { title: string; minutes?: number };

// Real per-lecture outline for "The Complete JavaScript Course: From Zero to
// Expert!" (Jonas Schmedtmann, 2025 ES2024/ES2025 edition — last updated 10/2025).
// Sourced from the public Udemy curriculum on 2026-06-26; keyed by CURRICULUM
// section id (Udemy section order maps 1:1 to lib/curriculum.ts). Includes every
// row in the section outline — video lectures, coding challenges, "Video Solution"
// lectures, practice assignments, summary PDFs and section quizzes — so rows
// without a video duration (challenges/quizzes/assignments) omit `minutes`.
// 345 rows across 21 sections. Editable: correct against a logged-in session later.
export const LESSONS: Record<number, Lesson[]> = {
  1: [
    { title: `Course Structure and Projects`, minutes: 5 },
    { title: `Read Before You Start!`, minutes: 1 },
    { title: `Watch Before You Start!`, minutes: 6 },
    { title: `Setting Up Our Code Editor`, minutes: 8 },
  ],
  2: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Hello World!`, minutes: 6 },
    { title: `A Brief Introduction to JavaScript`, minutes: 11 },
    { title: `Linking a JavaScript File`, minutes: 16 },
    { title: `Values and Variables`, minutes: 16 },
    { title: `Practice Assignments`, minutes: 1 },
    { title: `Data Types`, minutes: 19 },
    { title: `let, const and var`, minutes: 10 },
    { title: `Basic Operators`, minutes: 20 },
    { title: `Operator Precedence`, minutes: 11 },
    { title: `A Note About Challenges`, minutes: 1 },
    { title: `CHALLENGE #1` },
    { title: `CHALLENGE #1: Video Solution`, minutes: 7 },
    { title: `Strings and Template Literals`, minutes: 11 },
    { title: `Taking Decisions: if / else Statements`, minutes: 13 },
    { title: `CHALLENGE #2` },
    { title: `CHALLENGE #2: Video Solution`, minutes: 5 },
    { title: `Type Conversion and Coercion`, minutes: 17 },
    { title: `Truthy and Falsy Values`, minutes: 10 },
    { title: `Equality Operators: == vs. ===`, minutes: 16 },
    { title: `Boolean Logic`, minutes: 9 },
    { title: `Logical Operators`, minutes: 11 },
    { title: `CHALLENGE #3` },
    { title: `CHALLENGE #3: Video Solution`, minutes: 12 },
    { title: `The switch Statement`, minutes: 13 },
    { title: `Statements and Expressions`, minutes: 6 },
    { title: `The Conditional (Ternary) Operator`, minutes: 10 },
    { title: `CHALLENGE #4` },
    { title: `CHALLENGE #4: Video Solution`, minutes: 6 },
    { title: `JavaScript Releases: ES5, ES6+ and ESNext`, minutes: 14 },
    { title: `Section Summary PDF`, minutes: 1 },
    { title: `Test Your Fundamental Knowledge 1! Ready to Move On?` },
  ],
  3: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Activating Strict Mode`, minutes: 10 },
    { title: `Functions`, minutes: 19 },
    { title: `Function Declarations vs. Expressions`, minutes: 11 },
    { title: `Arrow Functions`, minutes: 10 },
    { title: `Functions Calling Other Functions`, minutes: 10 },
    { title: `Reviewing Functions`, minutes: 16 },
    { title: `CHALLENGE #1` },
    { title: `CHALLENGE #1: Video Solution`, minutes: 14 },
    { title: `Introduction to Arrays`, minutes: 22 },
    { title: `Basic Array Operations (Methods)`, minutes: 13 },
    { title: `CHALLENGE #2` },
    { title: `CHALLENGE #2: Video Solution`, minutes: 7 },
    { title: `Introduction to Objects`, minutes: 6 },
    { title: `Dot vs. Bracket Notation`, minutes: 19 },
    { title: `Object Methods`, minutes: 23 },
    { title: `CHALLENGE #3` },
    { title: `CHALLENGE #3: Video Solution`, minutes: 10 },
    { title: `Iteration: The for Loop`, minutes: 11 },
    { title: `Looping Arrays, Breaking and Continuing`, minutes: 22 },
    { title: `Looping Backwards and Loops in Loops`, minutes: 12 },
    { title: `The while Loop`, minutes: 12 },
    { title: `CHALLENGE #4` },
    { title: `CHALLENGE #4: Video Solution`, minutes: 11 },
    { title: `Section Summary PDF`, minutes: 1 },
    { title: `Test Your Fundamental Knowledge 2! Ready to Move On?` },
  ],
  4: [
    { title: `Pathways and Section Roadmaps`, minutes: 4 },
    { title: `Course Pathways`, minutes: 1 },
  ],
  5: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `Setting up Prettier and VS Code`, minutes: 16 },
    { title: `Installing Node.js and Setting Up a Dev Environment`, minutes: 12 },
    { title: `Learning How to Code`, minutes: 18 },
    { title: `Help Mike Learn How to Code` },
    { title: `How to Think Like a Developer: Become a Problem Solver!`, minutes: 11 },
    { title: `Help Sofia Think Like a Developer` },
    { title: `Using Google, StackOverflow and MDN`, minutes: 27 },
    { title: `Debugging (Fixing Errors)`, minutes: 5 },
    { title: `Debugging with the Console and Breakpoints`, minutes: 19 },
    { title: `CHALLENGE #1`, minutes: 15 },
    { title: `The Rise of AI Tools (ChatGPT, Copilot, Cursor AI, etc.)`, minutes: 18 },
    { title: `Solving CHALLENGE #2 With AI`, minutes: 17 },
  ],
  6: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Basic HTML Structure and Elements`, minutes: 10 },
    { title: `Attributes, Classes and IDs`, minutes: 13 },
    { title: `Basic Styling with CSS`, minutes: 12 },
    { title: `Introduction to the CSS Box Model`, minutes: 21 },
  ],
  7: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `PROJECT #1: Guess My Number!`, minutes: 9 },
    { title: `What's the DOM and DOM Manipulation`, minutes: 7 },
    { title: `Selecting and Manipulating Elements`, minutes: 8 },
    { title: `Handling Click Events`, minutes: 13 },
    { title: `Implementing the Game Logic`, minutes: 20 },
    { title: `Manipulating CSS Styles`, minutes: 8 },
    { title: `CHALLENGE #1`, minutes: 12 },
    { title: `Implementing Highscores`, minutes: 8 },
    { title: `Refactoring Our Code: The DRY Principle`, minutes: 15 },
    { title: `PROJECT #2: Modal Window`, minutes: 13 },
    { title: `Working With Classes`, minutes: 17 },
    { title: `Handling an "Esc" Keypress Event`, minutes: 14 },
    { title: `PROJECT #3: Pig Game`, minutes: 17 },
    { title: `Rolling the Dice`, minutes: 16 },
    { title: `Switching the Active Player`, minutes: 15 },
    { title: `Holding Current Score`, minutes: 25 },
    { title: `Resetting the Game`, minutes: 16 },
  ],
  8: [
    { title: `Section Intro`, minutes: 2 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `An High-Level Overview of JavaScript`, minutes: 12 },
    { title: `The JavaScript Engine and Runtime`, minutes: 14 },
    { title: `Execution Contexts and The Call Stack`, minutes: 18 },
    { title: `Scope and The Scope Chain`, minutes: 26 },
    { title: `Scoping in Practice`, minutes: 21 },
    { title: `Variable Environment: Hoisting and The TDZ`, minutes: 11 },
    { title: `Hoisting and TDZ in Practice`, minutes: 15 },
    { title: `The this Keyword`, minutes: 7 },
    { title: `The this Keyword in Practice`, minutes: 13 },
    { title: `Regular Functions vs. Arrow Functions`, minutes: 18 },
    { title: `Memory Management: Primitives vs. Objects`, minutes: 14 },
    { title: `Object References in Practice (Shallow vs. Deep Copies)`, minutes: 21 },
    { title: `Memory Management: Garbage Collection`, minutes: 15 },
  ],
  9: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `Destructuring Arrays`, minutes: 20 },
    { title: `Practice Assignments`, minutes: 1 },
    { title: `Destructuring Objects`, minutes: 20 },
    { title: `The Spread Operator (...)`, minutes: 21 },
    { title: `Rest Pattern and Parameters`, minutes: 19 },
    { title: `Short Circuiting (&& and ||)`, minutes: 16 },
    { title: `The Nullish Coalescing Operator (??)`, minutes: 4 },
    { title: `Logical Assignment Operators`, minutes: 12 },
    { title: `CHALLENGE #1`, minutes: 15 },
    { title: `Looping Arrays: The for-of Loop`, minutes: 7 },
    { title: `Enhanced Object Literals`, minutes: 7 },
    { title: `Optional Chaining (?.)`, minutes: 16 },
    { title: `Looping Objects: Object Keys, Values, and Entries`, minutes: 10 },
    { title: `CHALLENGE #2`, minutes: 15 },
    { title: `Sets`, minutes: 13 },
    { title: `New Operations to Make Sets Useful!`, minutes: 16 },
    { title: `Maps: Fundamentals`, minutes: 14 },
    { title: `Maps: Iteration`, minutes: 13 },
    { title: `Summary: Which Data Structure to Use?`, minutes: 10 },
    { title: `CHALLENGE #3`, minutes: 10 },
    { title: `Working With Strings - Part 1`, minutes: 17 },
    { title: `Working With Strings - Part 2`, minutes: 22 },
    { title: `Working With Strings - Part 3`, minutes: 22 },
    { title: `CHALLENGE #4`, minutes: 15 },
    { title: `String Methods Practice`, minutes: 17 },
  ],
  10: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `Default Parameters`, minutes: 9 },
    { title: `How Passing Arguments Works: Value vs. Reference`, minutes: 14 },
    { title: `First-Class and Higher-Order Functions`, minutes: 5 },
    { title: `Functions Accepting Callback Functions`, minutes: 15 },
    { title: `Functions Returning Functions`, minutes: 7 },
    { title: `The call and apply Methods`, minutes: 17 },
    { title: `The bind Method`, minutes: 22 },
    { title: `CHALLENGE #1`, minutes: 19 },
    { title: `Immediately Invoked Function Expressions (IIFE)`, minutes: 8 },
    { title: `Closures`, minutes: 22 },
    { title: `More Closure Examples`, minutes: 16 },
    { title: `CHALLENGE #2`, minutes: 5 },
  ],
  11: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `Simple Array Methods`, minutes: 17 },
    { title: `The New at Method`, minutes: 6 },
    { title: `Looping Arrays: forEach`, minutes: 14 },
    { title: `forEach With Maps and Sets`, minutes: 6 },
    { title: `PROJECT: "Bankist" App`, minutes: 10 },
    { title: `Creating DOM Elements`, minutes: 19 },
    { title: `CHALLENGE #1`, minutes: 9 },
    { title: `Data Transformations: map, filter, reduce`, minutes: 5 },
    { title: `The map Method`, minutes: 16 },
    { title: `Computing Usernames`, minutes: 12 },
    { title: `The filter Method`, minutes: 6 },
    { title: `The reduce Method`, minutes: 21 },
    { title: `CHALLENGE #2`, minutes: 10 },
    { title: `The Magic of Chaining Methods`, minutes: 20 },
    { title: `CHALLENGE #3`, minutes: 4 },
    { title: `The find Method`, minutes: 7 },
    { title: `Implementing Login`, minutes: 24 },
    { title: `Implementing Transfers`, minutes: 21 },
    { title: `The findIndex Method`, minutes: 13 },
    { title: `The New findLast and findLastIndex Methods`, minutes: 8 },
    { title: `some and every`, minutes: 15 },
    { title: `flat and flatMap`, minutes: 10 },
    { title: `CHALLENGE #4`, minutes: 24 },
    { title: `Sorting Arrays`, minutes: 22 },
    { title: `Array Grouping`, minutes: 13 },
    { title: `More Ways of Creating and Filling Arrays`, minutes: 21 },
    { title: `Non-Destructive Alternatives: toReversed, toSorted, toSpliced, with`, minutes: 6 },
    { title: `Summary: Which Array Method to Use?`, minutes: 11 },
    { title: `Array Methods Practice`, minutes: 32 },
    { title: `CHALLENGE #5`, minutes: 29 },
  ],
  12: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `Converting and Checking Numbers`, minutes: 17 },
    { title: `Math and Rounding`, minutes: 23 },
    { title: `The Remainder Operator`, minutes: 11 },
    { title: `Numeric Separators`, minutes: 7 },
    { title: `Working with BigInt`, minutes: 11 },
    { title: `Creating Dates`, minutes: 13 },
    { title: `Adding Dates to "Bankist" App`, minutes: 22 },
    { title: `Fixing a Sorting Bug`, minutes: 11 },
    { title: `Operations With Dates`, minutes: 15 },
    { title: `Internationalizing Dates (Intl)`, minutes: 17 },
    { title: `Internationalizing Numbers (Intl)`, minutes: 19 },
    { title: `Timers: setTimeout and setInterval`, minutes: 14 },
    { title: `Implementing a Countdown Timer`, minutes: 29 },
  ],
  13: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `PROJECT: "Bankist" Website`, minutes: 9 },
    { title: `How the DOM Really Works`, minutes: 11 },
    { title: `Selecting, Creating, and Deleting Elements`, minutes: 20 },
    { title: `Styles, Attributes and Classes`, minutes: 22 },
    { title: `Implementing Smooth Scrolling`, minutes: 16 },
    { title: `Types of Events and Event Handlers`, minutes: 11 },
    { title: `Event Propagation: Bubbling and Capturing`, minutes: 5 },
    { title: `Event Propagation in Practice`, minutes: 18 },
    { title: `Event Delegation: Implementing Page Navigation`, minutes: 19 },
    { title: `DOM Traversing`, minutes: 15 },
    { title: `Building a Tabbed Component`, minutes: 24 },
    { title: `Passing Arguments to Event Handlers`, minutes: 19 },
    { title: `Implementing a Sticky Navigation: The Scroll Event`, minutes: 8 },
    { title: `A Better Way: The Intersection Observer API`, minutes: 24 },
    { title: `Revealing Elements on Scroll`, minutes: 13 },
    { title: `Fixing a Small Scrolling Bug`, minutes: 5 },
    { title: `Lazy Loading Images`, minutes: 19 },
    { title: `Building a Slider Component: Part 1`, minutes: 23 },
    { title: `Building a Slider Component: Part 2`, minutes: 20 },
    { title: `Lifecycle DOM Events`, minutes: 9 },
    { title: `Efficient Script Loading: defer and async`, minutes: 14 },
  ],
  14: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `What is Object-Oriented Programming?`, minutes: 21 },
    { title: `OOP in JavaScript`, minutes: 10 },
    { title: `Constructor Functions and the new Operator`, minutes: 14 },
    { title: `Prototypes`, minutes: 15 },
    { title: `Prototypal Inheritance and The Prototype Chain`, minutes: 11 },
    { title: `Prototypal Inheritance on Built-In Objects`, minutes: 15 },
    { title: `CHALLENGE #1`, minutes: 7 },
    { title: `ES6 Classes`, minutes: 13 },
    { title: `Setters and Getters`, minutes: 13 },
    { title: `Static Methods`, minutes: 6 },
    { title: `Object.create`, minutes: 11 },
    { title: `CHALLENGE #2`, minutes: 6 },
    { title: `Inheritance Between "Classes": Constructor Functions`, minutes: 21 },
    { title: `CHALLENGE #3`, minutes: 11 },
    { title: `Inheritance Between "Classes": ES6 Classes`, minutes: 11 },
    { title: `Inheritance Between "Classes": Object.create`, minutes: 9 },
    { title: `Another Class Example`, minutes: 11 },
    { title: `Encapsulation: Private Class Fields and Methods`, minutes: 21 },
    { title: `Chaining Methods`, minutes: 7 },
    { title: `ES6 Classes Summary`, minutes: 7 },
    { title: `CHALLENGE #4`, minutes: 9 },
  ],
  15: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `Project Overview`, minutes: 5 },
    { title: `How to Plan a Web Project`, minutes: 18 },
    { title: `Help Maya Plan a Project` },
    { title: `Using the Geolocation API`, minutes: 8 },
    { title: `Displaying a Map Using Leaflet Library`, minutes: 14 },
    { title: `Displaying a Map Marker`, minutes: 20 },
    { title: `Rendering Workout Input Form`, minutes: 17 },
    { title: `Project Architecture`, minutes: 9 },
    { title: `Refactoring for Project Architecture`, minutes: 24 },
    { title: `Managing Workout Data: Creating Classes`, minutes: 16 },
    { title: `Creating a New Workout`, minutes: 34 },
    { title: `Rendering Workouts`, minutes: 24 },
    { title: `Move to Marker On Click`, minutes: 17 },
    { title: `Working with localStorage`, minutes: 26 },
    { title: `Final Considerations`, minutes: 6 },
  ],
  16: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `Asynchronous JavaScript, AJAX and APIs`, minutes: 18 },
    { title: `IMPORTANT: API URL Change`, minutes: 1 },
    { title: `Our First AJAX Call: XMLHttpRequest`, minutes: 20 },
    { title: `[OPTIONAL] How the Web Works: Requests and Responses`, minutes: 14 },
    { title: `Welcome to Callback Hell`, minutes: 14 },
    { title: `Promises and the Fetch API`, minutes: 9 },
    { title: `Consuming Promises`, minutes: 9 },
    { title: `Chaining Promises`, minutes: 9 },
    { title: `Handling Rejected Promises`, minutes: 16 },
    { title: `Throwing Errors Manually`, minutes: 15 },
    { title: `CHALLENGE #1`, minutes: 17 },
    { title: `Asynchronous Behind the Scenes: The Event Loop`, minutes: 18 },
    { title: `The Event Loop in Practice`, minutes: 9 },
    { title: `Building a Simple Promise`, minutes: 20 },
    { title: `Promisifying the Geolocation API`, minutes: 13 },
    { title: `CHALLENGE #2`, minutes: 16 },
    { title: `Consuming Promises with Async/Await`, minutes: 15 },
    { title: `Error Handling With try...catch`, minutes: 10 },
    { title: `Returning Values from Async Functions`, minutes: 15 },
    { title: `Running Promises in Parallel`, minutes: 11 },
    { title: `Other Promise Combinators: race, allSettled and any`, minutes: 13 },
    { title: `CHALLENGE #3`, minutes: 18 },
  ],
  17: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `An Overview of Modern JavaScript Development`, minutes: 7 },
    { title: `An Overview of Modules in JavaScript`, minutes: 15 },
    { title: `Exporting and Importing in ES6 Modules`, minutes: 23 },
    { title: `Top-Level await (ES2022)`, minutes: 15 },
    { title: `The Module Pattern`, minutes: 10 },
    { title: `CommonJS Modules`, minutes: 4 },
    { title: `A Brief Introduction to the Command Line`, minutes: 12 },
    { title: `Introduction to NPM`, minutes: 19 },
    { title: `Bundling With Parcel and NPM Scripts`, minutes: 22 },
    { title: `Configuring Babel and Polyfilling`, minutes: 18 },
    { title: `Review: Writing Clean and Modern JavaScript`, minutes: 10 },
    { title: `Let's Fix Some Bad Code: Part 1`, minutes: 23 },
    { title: `Declarative and Functional JavaScript Principles`, minutes: 12 },
    { title: `Let's Fix Some Bad Code: Part 2`, minutes: 38 },
  ],
  18: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `Project Overview and Planning (I)`, minutes: 14 },
    { title: `Latest Code Updates (IMPORTANT!)`, minutes: 1 },
    { title: `Loading a Recipe from API`, minutes: 24 },
    { title: `Rendering the Recipe`, minutes: 22 },
    { title: `Listening For load and hashchange Events`, minutes: 11 },
    { title: `The MVC Architecture`, minutes: 17 },
    { title: `Refactoring for MVC`, minutes: 39 },
    { title: `Helpers and Configuration Files`, minutes: 21 },
    { title: `Event Handlers in MVC: Publisher-Subscriber Pattern`, minutes: 15 },
    { title: `Implementing Error and Success Messages`, minutes: 12 },
    { title: `Implementing Search Results - Part 1`, minutes: 26 },
    { title: `Implementing Search Results - Part 2`, minutes: 28 },
    { title: `Implementing Pagination - Part 1`, minutes: 12 },
    { title: `Implementing Pagination - Part 2`, minutes: 37 },
    { title: `Project Planning II`, minutes: 3 },
    { title: `Updating Recipe Servings`, minutes: 27 },
    { title: `Developing a DOM Updating Algorithm`, minutes: 34 },
    { title: `Implementing Bookmarks - Part 1`, minutes: 26 },
    { title: `Implementing Bookmarks - Part 2`, minutes: 19 },
    { title: `Storing Bookmarks With localStorage`, minutes: 18 },
    { title: `Project Planning III`, minutes: 2 },
    { title: `Uploading a New Recipe - Part 1`, minutes: 18 },
    { title: `Uploading a New Recipe - Part 2`, minutes: 41 },
    { title: `Uploading a New Recipe - Part 3`, minutes: 20 },
    { title: `Wrapping Up: Final Considerations`, minutes: 15 },
  ],
  19: [
    { title: `Section Intro`, minutes: 1 },
    { title: `Section Roadmap`, minutes: 1 },
    { title: `Simple Deployment With Netlify`, minutes: 11 },
    { title: `Setting Up Git and GitHub`, minutes: 8 },
    { title: `Git Fundamentals`, minutes: 20 },
    { title: `Pushing to GitHub`, minutes: 10 },
    { title: `Setting Up Continuous Integration With Netlify`, minutes: 10 },
  ],
  20: [
    { title: `Where to Go from Here`, minutes: 3 },
    { title: `My Other Courses + Updates`, minutes: 1 },
  ],
  21: [
    { title: `Access the Old Course`, minutes: 1 },
  ],
};
